### ISSUE TITLE
Enable running only preprocessing

### ISSUE THREAD

**Issue by apeleraux** [cnio-bu/bollito#6]
Currently only some steps downstream of seurat_post_qc can be disabled as defined in the config file. It would be very useful to also be able to only run the preprocessing steps in bollito (i.e. stop before seurat object creation or before seurat postqc) and generate a report as users often need to tweak parameters of preprocessing and re-run preprocessing before moving to the next steps.

**Comment by apeleraux** [comment]
I actually found that this is already possible, just specifying a different target rule in the snakemake commands, for example using the expression_matrix rule as target: 
snakemake --use-conda -j 92  expression_matrix
snakemake expression_matrix --report report.zip  
So in my opinion, the issue can be closed.

**Comment by tdido** [comment]
Thank you, Annick. We'll take a look at improving the documentation to make the usage of the different entry points clearer.
